---
{{ $randNum := randNumeric 3 }}
apiVersion: v1
kind: Pod
metadata:
  name: mec-iot-client-{{$randNum}}
  labels:
    app: mec-iot-client-{{$randNum}}
spec:
  #hostNetwork: true
  #dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: mec-iot-client-1
      image: davideborsatti/cnsm-iot-client
      env:
        # MEC Platform endpoint
        - name: MEC_BASE
          value: "http://mec-platform"
        - name: INFRA
          value: "k8s"  
        - name: MY_POD_NAME
          value: "mec-iot-client-{{$randNum}}"
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      imagePullPolicy: Always
  #nodeSelector:
  #  project: mec
---
apiVersion: v1
kind: Service
metadata:
  name: mec-iot-client-{{$randNum}}
spec:
  type: LoadBalancer
  selector:
    app: mec-iot-client-{{$randNum}}
  ports:
    - port: 80
      targetPort: 80





