---
{{ $randNum := randNumeric 3 }}
apiVersion: v1
kind: Pod
metadata:
  name: opcua-server-{{$randNum}}   
  labels:
    app: opcua-server-{{$randNum}}
spec:
  #hostNetwork: true
  #dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: opcua-server-1
      image: lorenzobassi/opcua_server_mec-cnsm
      env:
        # MEC Platform endpoint
        - name: MEC_BASE
          value: "http://mec-platform"
        - name: INFRA
          value: "k8s"  
        - name: MY_POD_NAME
          value: "opcua-server-{{$randNum}}"
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace        
      ports:
        - containerPort: 4840
      imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: opcua-server-{{$randNum}}
spec:
  type: LoadBalancer
  selector:
    app: opcua-server-{{$randNum}}
  ports:
    - port: 4840
      targetPort: 4840

